@baseUrlLocal = http://localhost:4004
@usernameBTP = {{$dotenv BTP-USER}}
@passwordBTP= {{$dotenv BTP-PASSWORD}}

### login 
# @name tokenPAYDEV
GET https://spro-pay-as-you-go-nra66r3d.authentication.br10.hana.ondemand.com/oauth/token
    ?grant_type=password
    &username={{usernameBTP}}
    &password={{passwordBTP}}
Content-Type: 'application/x-www-form-urlencoded'
Authorization: Basic {{$dotenv USER-XSUAA}}:{{$dotenv PASS-XSUAA}}

@token = {{tokenPAYDEV.response.body.access_token}}


### Teste de conexão com CAP CDS Client API
### ============================================
GET {{baseUrlLocal}}/logs-services/logs
Authorization: Bearer {{token}}


### GET
GET {{baseUrlLocal}}/ogs-services/logs
Authorization: Bearer {{token}}


### GET
GET {{baseUrlLocal}}/sap-services/checkService(serviceName='SolicitationsSet', top=5)
Authorization: Bearer {{token}}

### GET
GET {{baseUrlLocal}}/sap/opu/odata/sprolims/SRV_LABSERV_SRV/$metadata
Authorization: Bearer {{token}}

### GET
GET {{baseUrlLocal}}/sap/opu/odata/sprolims/SRV_LABSERV_SRV/SolicitationsSet?$top=5
Authorization: Bearer {{token}}

### GET
GET {{baseUrlLocal}}/sap/opu/odata/sprolims/SRV_LABSERV_SRV/SolicitationsSet/$count
Authorization: Bearer {{token}}


### GET
GET {{baseUrlLocal}}/sap/opu/odata/sprolims/SRV_LABSERV_SRV/SolicitationsSet?$skip=0&$top=20&$orderby=solicitation_id%20desc
Authorization: Bearer {{token}}